#端口号
server:
  port: 82

#数据库链接设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ""

#整合Mybatis
mybatis:
  #  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: com.boot.wyb.entity
  #  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml
#  多层级目录  mapper-locations: classpath:mapper/**/**.xml


#  打印 sql 扫描dao层
logging:
  level:
    com:
      boot:
        yunxiaodefengdemo:
          Dao:  debug